### ISSUE TITLE
I am facing an error related to libgtk2.0-dev and pkg-config

### ISSUE THREAD

**Issue by Deepak3994** [rohanchandra30/TrackNPred#11]
Hi,

I get the below error when i try to execute train script from the framework.

[ERROR] OpenCV(4.1.1) /io/opencv/modules/highgui/src/window.cpp:693: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey' 
[ERROR] Traceback (most recent call last):
[ERROR] File "/home/deepaknayak/Documents/openproject-status/TrackNPred/control/trainThread.py", line 126, in run
[ERROR] self.track(self.args)
[ERROR] File "/home/deepaknayak/Documents/openproject-status/TrackNPred/control/trainThread.py", line 94, in track
[ERROR] self.model.tracking(dataDir, data_folder, thread=self)
[ERROR] File "/home/deepaknayak/Documents/openproject-status/TrackNPred/model/model.py", line 129, in tracking
[ERROR] densepeds(dataDir, data_folder, display, thread)
[ERROR] File "/home/deepaknayak/Documents/openproject-status/TrackNPred/model/Tracking/DensePeds.py", line 307, in densepeds
[ERROR] run(sequence_dir, detection_file, output_file, matlab_file, min_conf, nms, min_det_ht, max_cos_dist, nn_budget, disp, thread)
[ERROR] File "/home/deepaknayak/Documents/openproject-status/TrackNPred/model/Tracking/DensePeds.py", line 228, in run
[ERROR] visualizer.run(frame_callback, thread)
[ERROR] File "/home/deepaknayak/Documents/openproject-status/TrackNPred/model/Tracking/application_util/visualization.py", line 152, in run
[ERROR] self.viewer.run(lambda: self._update_fun(frame_callback, thread))
[ERROR] File "/home/deepaknayak/Documents/openproject-status/TrackNPred/model/Tracking/application_util/image_viewer.py", line 506, in run
[ERROR] key = cv2.waitKey(remaining_time)
[ERROR] cv2.error: OpenCV(4.1.1) /io/opencv/modules/highgui/src/window.cpp:693: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvWaitKey'

Kindly help..

**Comment by sankhanrsss** [comment]
Sometimes common sense is required. I guess you should have minimal sense

**Comment by rohanchandra30** [comment]
The error stems from the waitkey function in opencv located [here](https://github.com/rohanchandra30/TrackNPred/blob/3cf1dfca7e98f86e67561b6327c210d84a50cdd4/model/Tracking/application_util/image_viewer.py#L506)

Comment out this and the following relevant lines containing mentions of "key" and you should be fine. Let me know if this works.
