### ISSUE TITLE
 Question of predicted trajectory images

### ISSUE THREAD

**Issue by Xuedixuedi** [rohanchandra30/TrackNPred#17]

**Comment by Xuedixuedi** [comment]
Hello, when I used this project, I found that at most I can only get tracked images, but not predicted trajectory images. Then, where is the output of the predicted trajectory data, and how do I use it? I'm sorry that I am a beginner, and the questions I may ask are a little simple, so please answer me, thank you.

**Comment by christian-rncl** [comment]
This sounds like issue #16 . Unfortunately, this framework doesn't plot/visualize predicted trajectories at this moment.
