### ISSUE TITLE
How to do inference on sample video?

### ISSUE THREAD

**Issue by chowkamlee81** [rohanchandra30/TrackNPred#3]
Kindly suggest how to do inference on sample video?
I pressed evaluate button, but GUI window closed after few seconds with message below:

/home/user/.local/lib/python3.5/site-packages/torch/nn/modules/rnn.py:54: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
[INFO: engine.py:  340]: Engine run starting with max_epochs=1.

Process finished with exit code 136 (interrupted by signal 8: SIGFPE)

KINDLY HELP

**Comment by christian-rncl** [comment]
Hello,

What settings you’re using: prediction algo, model path etc...

**Comment by chowkamlee81** [comment]
Hi,
I have used below configurations. Kindly help
Dir : resources/data/TRAF
YOLO
Traphic
Traphic_2019_07_26_00_25_model.tar

After pressing Evaluate button, It stopped with mesaage in GUI below:
 
INFO] Evaluation started...
[INFO]: Using Traphic for the saved model
./resources/trained_models/Traphic_2019_07_26_00_25_model.tar
[INFO]: model loaded
[INFO]: Using CUDA
[INFO]: Optimizer: Adam ( Parameter Group 0 amsgrad: False betas: (0.9, 0.999) eps: 1e-08 lr: 0.001 weight_decay: 0 )
[INFO]: Loss: BCELoss()
[INFO]: *** Evaluating Prediction Model ***

**Comment by chowkamlee81** [comment]
@rohanchandra30 @christian-rncl , 

Can you please tell me how to do inference of the model either using GUI/command line. Kindly help

**Comment by christian-rncl** [comment]
Sorry for the late response, I was away from my machine for a while. Is this still a problem for you? I won’t be able to try and replicate it for a bit

**Comment by chowkamlee81** [comment]
Yeah problem is still persisting..
I was trying to use python main_cmd.py --list 13 --detection False --tracking False --train False --eval True

I got the message below and doesn't even move a single line. I guess it got stucked.:
Start spliting data...
Dataset 13 finsihed.
Training file saved and ready.
Done merging data for training.
Start evaluating...
Backend TkAgg is interactive backend. Turning interactive mode on.
