### ISSUE TITLE
Core dump error during training

### ISSUE THREAD

**Issue by rabiaali95** [rohanchandra30/TrackNPred#7]
The network successfully trains for few epochs (8-9) and then it throws an error Floating point exception (core dumped)
Can anyone help what could be the possible reason and how to fix it?

**Comment by rohanchandra30** [comment]
It is possibly to do with the dataset you are using. Even we bumped into this issue with a particular sequence of TRAF, which we were unable to resolve, but then we tried with another video and it worked. We're currently trying to figure out this issue ourselves.

But do let us know if it worked with another video. Apologies for the late response. I had some deadlines this weekend.
